### ISSUE TITLE
`isIdentifier` acts as a type guard when it shouldn’t

### ISSUE THREAD

**Issue by selrond** [sindresorhus/is-identifier#1]
Here https://github.com/sindresorhus/is-identifier/blob/f1222ac0a28b04d91d0e83bd25a08c8bbde0968d/index.d.ts#L18C1-L18C7 there’s a type predicate, where the value is narrowed to be a string when `isIdentifier` returns `true`. 

Consider the following example:

```tsx
export const constructJsonPath = (segments: Array<string>) => {
  if (isEmpty(segments)) {
    return ''
  }
  return segments.reduce((path, currentSegment) => {
    if (currentSegment === '') {
      return path
    }
    if (isIdentifier(currentSegment)) {
      return path ? `${path}.${currentSegment}` : currentSegment
    }
    // string with spaces or an integer for instance is not a valid identifier, but still a string.
    const segment = `["${currentSegment as string}"]`
    return path ? `${path}${segment}` : segment
  }, '')
}
```

The `isIdentifier` thus acts as a type guard when it shouldn’t.

Here’s a TS playground: https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBMAzgSQCYFMB2NgDNjpRy5QQhwDkSAtMBtngVBQFCiSxwDeCiAouBgBPOAF9ipchQA2EVAENEAC1Yt0ADw7wAxhEyIdeg1ACu2mAClEegAryYSuAF44ACkToA5iCwxEALjgAQSgoeSEAHmNgTE8APgBKZzjuFjgEXDckATBhdy8fbEQEpK409LgodBgTKExKVnTRcqqaurgPb19EADoq1DN0V1cweyUAGjhtWqrsAGUC3ySnFLKKjLdp0N8FruxnJxcKClLy9dba+tGHM7FbvCyUehx8Qlct2ZhdwpgS1PX0hd2tdHAB+OAAAwAJFwQaIejCPjtFthRBC4IEkfMUTBbukAPT4gHEkkAgB6oNuzXWhI6MCgMU8cAA7sAHB1Rtp0Ig4NA4PJ6jEYF5CMQ+TEDAKubw4JgIPB5HAAG7yaR0BDPRiESYAIxM8AMwGk0n5dIZsR6t10+gNOOckIA2gAiREzZF7BU86KxUROgC6ENutNJIbgFNuQKuYzg4OhsLGohhnR+aIxHRx5VEk2OCRYzSAA

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/is-identifier/releases/tag/v1.0.1
